feat: implement custom inflation
elesto-dao/elesto pull request #104
Opened 2022-05-04 18:02 UTC by noandrea

inflation is scheduled to decrease each year until reaching 1bn tokens from an initial supply of 200ml tokens

2022-06-13 13:43 UTC, barriebyron reviewed
cool, a better mint module! see suggested changes for grammar grooming

2022-06-13 13:43 UTC, barriebyron commented on x/mint/spec/01_concepts.md
> +targeting a particular bonded-stake ratio, this `mint` module is cutomized to use a constant inflation rate. The module
```suggestion
targeting a particular bonded-stake ratio, this `mint` module is customized to use a constant inflation rate. The module
```

2022-06-13 13:43 UTC, barriebyron commented on x/mint/spec/01_concepts.md
> +decimal loss.
```suggestion
mints in relation to the block time with the pre-defined inflation schedule in params. It is possible that the actual
minted amount for the schedule is less than the pre-defined inflation schedule amount due to the block time delay and
decimal loss.
```

2022-06-13 13:43 UTC, barriebyron commented on x/mint/spec/01_concepts.md
> +decimal loss.
do we mean "mints in relation to the block time" 
or
"mints are relative to the block time"
?

2022-06-13 13:43 UTC, barriebyron commented on x/mint/spec/02_state.md
> +| `blocks_per_year` | `int64`  | estimate number of blocks in a year             |
```suggestion
| `blocks_per_year` | `int64`  | estimated number of blocks in a year             |
```

2022-06-13 13:43 UTC, barriebyron commented on x/mint/spec/03_begin_block.md
> +`LastBlockTime`.
```suggestion
and sets `LastBlockTime` value. 

**Note:** There is no inflation in the genesis block because the genesis block doesn't have
`LastBlockTime`.
```

2022-06-13 22:38 UTC, noandrea commented
@gsora I cannot review the PR because I opened it, but LGTM :zap:  !

2022-06-15 06:48 UTC, PaddyMc requested changes
Great work on this guys! :mage: 

I found a few issues, I opened PR https://github.com/elesto-dao/elesto/pull/141 explaining the issues with suggested fixes, please have a look when you get a chance! :bow:

2022-06-15 06:48 UTC, PaddyMc commented on x/mint/abci_test.go
> +	const defaultTolerance = int64(4) // https://xkcd.com/221/
:joy:

2022-06-15 06:48 UTC, PaddyMc commented on x/mint/abci.go
> +	BlockInflationAmount = map[int]int64{
Do we need to target `micro tokens` here?

```
	BlockInflationAmount = map[int]int64{
		1:  31709792000000,
		2:  31709792000000,
		3:  23782344000000,
		4:  14863965000000,
		5:  8360980000000,
		6:  4441771000000,
		7:  2931569000000,
		8:  2990200000000,
		9:  3050004000000,
		10: 2998751000000,
	}
```

This could also fix the issue that when we are calculating years 5 and later we will always get 0 for inflation rewards

2022-06-15 06:48 UTC, PaddyMc commented on x/mint/abci.go
> +	inflationYear := int(math.Floor(float64(ctx.BlockHeight()) / float64(blocksPerYear)))
here for the first year, we have 0 inflation

```
> github.com/elesto-dao/elesto/x/mint.BeginBlocker() /home/ghost/git/elesto-dao/elesto/x/mint/abci.go:48 (PC: 0x23b4dd8)
    43:		defer telemetry.ModuleMeasureSince(types.ModuleName, time.Now(), telemetry.MetricKeyBeginBlocker)
    44:	
    45:		params := k.GetParams(ctx)
    46:	
    47:		// calculate inflation
=>  48:		inflationYear := int(math.Floor(float64(ctx.BlockHeight()) / float64(blocksPerYear)))
    49:	
    50:		inflationAmount, ok := BlockInflationAmount[inflationYear]
    51:		if !ok {
    52:			return
    53:		}
(dlv) p params
github.com/elesto-dao/elesto/x/mint/types.Params {
	MintDenom: "stake",
	BlocksPerYear: 6308000,
	MaxSupply: 1000000000000000,
	TeamAddress: "elesto1ms2wrq8k04cug7ea6ekf60nfke6a8vu8pwm684",
	TeamReward: "0.1",}
(dlv) n
> github.com/elesto-dao/elesto/x/mint.BeginBlocker() /home/ghost/git/elesto-dao/elesto/x/mint/abci.go:50 (PC: 0x23b4e80)
    45:		params := k.GetParams(ctx)
    46:	
    47:		// calculate inflation
    48:		inflationYear := int(math.Floor(float64(ctx.BlockHeight()) / float64(blocksPerYear)))
    49:	
=>  50:		inflationAmount, ok := BlockInflationAmount[inflationYear]
    51:		if !ok {
    52:			return
    53:		}
    54:	
    55:		mintedCoin := sdk.NewCoin(params.MintDenom, sdk.NewInt(inflationAmount))
(dlv) n
> github.com/elesto-dao/elesto/x/mint.BeginBlocker() /home/ghost/git/elesto-dao/elesto/x/mint/abci.go:51 (PC: 0x23b4ecc)
    46:	
    47:		// calculate inflation
    48:		inflationYear := int(math.Floor(float64(ctx.BlockHeight()) / float64(blocksPerYear)))
    49:	
    50:		inflationAmount, ok := BlockInflationAmount[inflationYear]
=>  51:		if !ok {
    52:			return
    53:		}
    54:	
    55:		mintedCoin := sdk.NewCoin(params.MintDenom, sdk.NewInt(inflationAmount))
    56:		mintedCoins := sdk.NewCoins(mintedCoin)
(dlv) p inflationAmount
0
(dlv) p inflationYear
0
(dlv) p blockPerYear
Command failed: could not find symbol value for blockPerYear
(dlv) p blocksPerYear
6307200
(dlv) call ctx.BlockHeight()
6:37AM INF Timed out dur=3000 height=187 module=consensus round=0 step=3
6:39AM INF Saving AddrBook to file book=/home/ghost/.elesto/config/addrbook.json module=p2p size=0
6:39AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
> github.com/elesto-dao/elesto/x/mint.BeginBlocker() /home/ghost/git/elesto-dao/elesto/x/mint/abci.go:51 (PC: 0x23b4ecc)
Values returned:
	~r0: 187

    46:	
    47:		// calculate inflation
    48:		inflationYear := int(math.Floor(float64(ctx.BlockHeight()) / float64(blocksPerYear)))
    49:	
    50:		inflationAmount, ok := BlockInflationAmount[inflationYear]
=>  51:		if !ok {
    52:			return
    53:		}
    54:	
    55:		mintedCoin := sdk.NewCoin(params.MintDenom, sdk.NewInt(inflationAmount))
    56:		mintedCoins := sdk.NewCoins(mintedCoin)

```

2022-06-15 08:51 UTC, gsora commented on x/mint/spec/01_concepts.md
> +decimal loss.
> "mints in relation to the block time"

I'd say this!

2022-06-15 14:33 UTC, gsora commented on x/mint/abci.go
> +	BlockInflationAmount = map[int]int64{
We are actually, those are already microtokens!

Given the [simulation spreadsheet](https://docs.google.com/spreadsheets/d/1sXwR-cYHS98in1aMzBabF7FNjqikbA3btnPMlFqgQ50/edit#gid=0), the amount of tokens you see listed there are what we're expecting to be produced in each block.

2022-06-15 15:11 UTC, gsora commented on x/mint/abci.go
> +	inflationYear := int(math.Floor(float64(ctx.BlockHeight()) / float64(blocksPerYear)))
Fixed! Thanks <3

2022-06-15 15:18 UTC, merged